version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: notesapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    container_name: notes-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=mydb

volumes:
  mongo-data:
